# Generated by Django 5.2.12 on 2026-04-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='doctors_images', verbose_name='Фото'),
        ),
    ]
